apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mj4tggk7h-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mj4tggk7h-python 
  name: mj4tggk7h-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mj4tggk7h-python 
